return {
  require('lightboat.plugin.code.blink_cmp'),
  -- color = require('lightboat.plugin.code.color'),
  -- comment = require('lightboat.plugin.code.comment'),
  require('lightboat.plugin.code.conform'),
  -- dap = require('lightboat.plugin.code.dap'),
  -- interesting_words = require('lightboat.plugin.code.interesting_words'),
  require('lightboat.plugin.code.lsp'),
  require('lightboat.plugin.code.mason'),
  -- nvim_dap_go = require('lightboat.plugin.code.nvim_dap_go'),
  -- nvim_jdtls = require('lightboat.plugin.code.nvim_jdtls'),
  -- pair = require('lightboat.plugin.code.pair'),
  -- overseer = require('lightboat.plugin.code.overseer'),
  -- todo = require('lightboat.plugin.code.todo'),
}
