return {
  enabled = true,
  keys = {
    ['<leader>ay'] = { key = '<leader>ay', mode = 'n', desc = 'Yank current file to + reg' },
    ['<m-x>'] = { key = '<m-x>', mode = { 'n', 'x' }, desc = 'Cut to + reg' },
    ['<m-a>'] = { key = '<m-a>', mode = { 'n', 'x', 'i' }, desc = 'Select all' },
    ['<c-u>'] = { key = '<c-u>', mode = 'i', desc = 'Delete to start of line' },
    -- TODO: support in cmd line with non-ascii
    ['<c-w>'] = { key = '<c-w>', mode = 'i', desc = 'Delete one word backwards' },
    ['<c-a>'] = { key = '<c-a>', mode = { 'x', 'i', 'c' }, expr = true, desc = 'Move cursor to start of line' },
    ['<c-e>'] = { key = '<c-e>', mode = { 'x', 'i', 'c' }, desc = 'Move cursor to end of line' },
    ['<leader>l'] = { key = '<leader>l', mode = 'n', desc = 'Split right' },
    ['<leader>j'] = { key = '<leader>j', mode = 'n', desc = 'Split below' },
    ['<leader>h'] = { key = '<leader>h', mode = 'n', desc = 'Split right' },
    ['<leader>k'] = { key = '<leader>k', mode = 'n', desc = 'Split above' },
    ['='] = { key = '=', mode = 'n', desc = 'Equalize windows' },
    ['<c-h>'] = { key = '<c-h>', mode = 'n', desc = 'Cursor left' },
    ['<c-j>'] = { key = '<c-j>', mode = 'n', desc = 'Cursor down' },
    ['<c-k>'] = { key = '<c-k>', mode = 'n', desc = 'Cursor up' },
    ['<c-l>'] = { key = '<c-l>', mode = 'n', desc = 'Cursor right' },
    ['<leader>T'] = { key = '<leader>T', mode = 'n', desc = 'Move current window to a new tabpage' },
    ['<leader>t2'] = { key = '<leader>t2', mode = 'n', desc = 'Set tab with 2 spaces' },
    ['<leader>t4'] = { key = '<leader>t4', mode = 'n', desc = 'Set tab with 4 spaces' },
    ['<leader>t8'] = { key = '<leader>t8', mode = 'n', desc = 'Set tab with 8 spaces' },
    ['<leader>tt'] = { key = '<leader>tt', mode = 'n', desc = 'Toggle expandtab' },
    ['F'] = { key = 'F', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Previous find character' },
    ['T'] = { key = 'T', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Previous till character' },
    ['f'] = { key = 'f', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Next find character' },
    ['t'] = { key = 't', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Next till character' },
    ['b'] = { key = 'b', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Previous word' },
    ['w'] = { key = 'w', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Next word' },
    ['B'] = { key = 'B', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Previous big word' },
    ['W'] = { key = 'W', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Next big word' },
    ['ge'] = { key = 'ge', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Previous end word' },
    ['e'] = { key = 'e', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Next end word' },
    ['gE'] = { key = 'gE', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Previous big end word' },
    ['E'] = { key = 'E', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Next big end word' },
    ['N'] = { key = 'N', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Previous search pattern' },
    ['n'] = { key = 'n', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Next search pattern' },
    ['[s'] = { key = '[s', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Previous misspelled word' },
    [']s'] = { key = ']s', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Next misspelled word' },
    ['[z'] = { key = '[z', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Move to start of current fold' },
    [']z'] = { key = ']z', mode = { 'n', 'o', 'x' }, expr = true, desc = 'Move to end of current fold' },
    ['zk'] = { key = 'zk', mode = { 'n', 'o', 'x' }, expr = true, desc = 'To the end of the previous fold' },
    ['zj'] = { key = 'zj', mode = { 'n', 'o', 'x' }, expr = true, desc = 'To the start of the next fold' },
    ['<c-n>'] = { key = '<c-n>', mode = 'i' },
    ['<c-p>'] = { key = '<c-p>', mode = 'i' },
    ['<leader>sc'] = { key = '<leader>sc', mode = 'n', desc = 'Toggle spell check' },
    ['<leader>ts'] = { key = '<leader>ts', mode = 'n', desc = 'Toggle treesitter highlight' },
    ['<leader>i'] = { key = '<leader>i', mode = 'n', desc = 'Toggle inlay hints' },
  },
}
