return {
  enabled = true,
  delete_default_commant = true,
  delete_default_diagnostic_under_cursor = true,
  disable_default_find_match_in_inserat = true,
  separate_operator = {
    ya = true,
    yi = true,
    ca = true,
    ci = true,
    da = true,
    di = true,
  },
  keys = {
    ['<m-x>'] = { key = '<m-x>', mode = { 'n', 'x' }, desc = 'Cut to + reg' },
    ['<m-a>'] = {
      key = '<m-a>',
      prev = 'disable_snacks_animate_scroll_once',
      mode = { 'n', 'x', 'i' },
      expr = true,
      desc = 'Select all',
    },
    ['<c-u>'] = { key = '<c-u>', mode = 'i', desc = 'Delete to start of line' },
    ['<c-w>'] = { key = '<c-w>', mode = 'i', expr = true, remap = true, desc = 'Delete one word backwards' },
    ['<c-a>'] = { key = '<c-a>', mode = { 'i', 'c' }, expr = true, desc = 'Move cursor to start of line' },
    ['<c-e>'] = { key = '<c-e>', mode = { 'i', 'c' }, expr = true, desc = 'Move cursor to end of line' },
    ['<leader>l'] = { key = '<leader>l', desc = 'Split right' },
    ['<leader>j'] = { key = '<leader>j', desc = 'Split below' },
    ['<leader>h'] = { key = '<leader>h', desc = 'Split right' },
    ['<leader>k'] = { key = '<leader>k', desc = 'Split above' },
    ['='] = { key = '=', desc = 'Equalize windows' },
    ['<c-h>'] = { key = '<c-h>', desc = 'Cursor left' },
    ['<c-j>'] = { key = '<c-j>', desc = 'Cursor down' },
    ['<c-k>'] = { key = '<c-k>', expr = true, mode = { 'n', 'i' }, desc = 'Cursor up or delete to end of line' },
    ['<c-l>'] = { key = '<c-l>', desc = 'Cursor right' },
    ['<leader>T'] = { key = '<leader>T', desc = 'Move current window to a new tabpage' },
    ['<leader>t2'] = { key = '<leader>t2', desc = 'Set tab with 2 spaces' },
    ['<leader>t4'] = { key = '<leader>t4', desc = 'Set tab with 4 spaces' },
    ['<leader>t8'] = { key = '<leader>t8', desc = 'Set tab with 8 spaces' },
    ['<leader>tt'] = { key = '<leader>tt', desc = 'Toggle expandtab' },
    ['F'] = { key = 'F', mode = { 'n', 'x' }, expr = true, desc = 'Previous find character' },
    ['T'] = { key = 'T', mode = { 'n', 'x' }, expr = true, desc = 'Previous till character' },
    ['f'] = { key = 'f', mode = { 'n', 'x' }, expr = true, desc = 'Next find character' },
    ['t'] = { key = 't', mode = { 'n', 'x' }, expr = true, desc = 'Next till character' },
    ['b'] = { key = 'b', mode = { 'n', 'x' }, expr = true, desc = 'Previous word' },
    ['w'] = { key = 'w', mode = { 'n', 'x' }, expr = true, desc = 'Next word' },
    ['B'] = { key = 'B', mode = { 'n', 'x' }, expr = true, desc = 'Previous big word' },
    ['W'] = { key = 'W', mode = { 'n', 'x' }, expr = true, desc = 'Next big word' },
    ['ge'] = { key = 'ge', mode = { 'n', 'x' }, expr = true, desc = 'Previous end word' },
    ['e'] = { key = 'e', mode = { 'n', 'x' }, expr = true, desc = 'Next end word' },
    ['gE'] = { key = 'gE', mode = { 'n', 'x' }, expr = true, desc = 'Previous big end word' },
    ['E'] = { key = 'E', mode = { 'n', 'x' }, expr = true, desc = 'Next big end word' },
    ['N'] = { key = 'N', mode = { 'n', 'x' }, expr = true, desc = 'Previous search pattern' },
    ['n'] = { key = 'n', mode = { 'n', 'x' }, expr = true, desc = 'Next search pattern' },
    ['[s'] = { key = '[s', mode = { 'n', 'x' }, expr = true, desc = 'Previous misspelled word' },
    [']s'] = { key = ']s', mode = { 'n', 'x' }, expr = true, desc = 'Next misspelled word' },
    ['[z'] = { key = '[z', mode = { 'n', 'x' }, expr = true, desc = 'Move to start of current fold' },
    [']z'] = { key = ']z', mode = { 'n', 'x' }, expr = true, desc = 'Move to end of current fold' },
    ['zk'] = { key = 'zk', mode = { 'n', 'x' }, expr = true, desc = 'To the end of the previous fold' },
    ['zj'] = { key = 'zj', mode = { 'n', 'x' }, expr = true, desc = 'To the start of the next fold' },
    ['<leader>sc'] = { key = '<leader>sc', desc = 'Toggle spell check' },
    ['<leader>ts'] = { key = '<leader>ts', desc = 'Toggle treesitter highlight' },
    ['<leader>i'] = { key = '<leader>i', desc = 'Toggle inlay hints' },
    ['<m-d>'] = { key = '<m-d>', mode = 'i', desc = 'Delete word forwards' },
    ['<m-p>'] = { key = '<m-p>', mode = 'n', desc = 'Same with :put' },
    ['<m-P>'] = { key = '<m-P>', mode = 'n', desc = 'Same with :put!' },
  },
}
