return {
  enabled = true,
  enable_spell_check = true,
  max_search_lines = 10,
  keys = {
    ['f'] = { key = 'f', mode = 'i', buffer = true, expr = true },
    ['1'] = { key = '1', mode = 'i', buffer = true, expr = true },
    ['2'] = { key = '2', mode = 'i', buffer = true, expr = true },
    ['3'] = { key = '3', mode = 'i', buffer = true, expr = true },
    ['4'] = { key = '4', mode = 'i', buffer = true, expr = true },
    ['a'] = { key = 'a', mode = 'i', buffer = true, expr = true },
    ['b'] = { key = 'b', mode = 'i', buffer = true, expr = true },
    ['c'] = { key = 'c', mode = 'i', buffer = true, expr = true },
    ['s'] = { key = 's', mode = 'i', buffer = true, expr = true },
    ['t'] = { key = 't', mode = 'i', buffer = true, expr = true },
    ['T'] = { key = 'T', mode = 'i', buffer = true, expr = true },
    ['m'] = { key = 'm', mode = 'i', buffer = true, expr = true },
    ['d'] = { key = 'd', mode = 'i', buffer = true, expr = true },
    ['i'] = { key = 'i', mode = 'i', buffer = true, expr = true },
    ['M'] = { key = 'M', mode = 'i', buffer = true, expr = true },
    ['o'] = { key = 'o', mode = 'n', buffer = true, remap = true },
    ['<cr>'] = { key = '<cr>', mode = 'i', buffer = true },
    ['<bs>'] = { key = '<bs>', mode = 'i', buffer = true },
    ['<tab>'] = { key = '<tab>', mode = 'i', buffer = true },
    ['gx'] = { key = 'gx', mode = { 'n', 'x' }, buffer = true, desc = 'Toggler check boxes' },
  },
}
