return {
  enabled = true,
  restore_anonymous_reg = true,
  keys = {
    ['y'] = {
      key = 'y',
      mode = { 'n', 'x', 'o' },
      expr = true,
      opts = { consider_wrap = false, consider_invisible = true, increase_count = true },
    },
    ['p'] = { key = 'p', mode = { 'n', 'x' } },
    ['gp'] = { key = 'gp', mode = { 'n', 'x' } },
    ['gP'] = { key = 'gP', mode = { 'n', 'x' } },
    ['P'] = { key = 'P', mode = { 'n', 'x' } },
    ['Y'] = {
      key = 'Y',
      expr = true,
      desc = 'Line wise yank',
      opts = { consider_wrap = false, consider_invisible = true, increase_count = true },
    },
    ['<leader>Y'] = {
      key = '<leader>Y',
      expr = true,
      desc = 'Line wise yank to + reg',
      opts = { consider_wrap = false, consider_invisible = true, increase_count = true },
    },
    ['<leader>y'] = { key = '<leader>y', expr = true, desc = 'Yank to + reg', mode = { 'n', 'x' } },
    ['<m-c>'] = { key = '<m-c>', mode = { 'n', 'x' }, expr = true, desc = 'Copy to + reg' },
    ['<c-rightmouse>'] = {
      key = '<c-rightmouse>',
      prev = 'try_to_paste_image_p_with_curl',
      expr = true,
      desc = 'Paste from + reg',
      mode = { 'n', 'x', 'i' },
    },
    ['<m-v>'] = {
      key = '<m-v>',
      prev = 'try_to_paste_image_p',
      desc = 'Paste from + reg',
      mode = { 'n', 'x', 'i', 'c' },
      expr = true,
    },
    ['<leader>p'] = {
      key = '<leader>p',
      prev = 'try_to_paste_image_p',
      expr = true,
      desc = 'Paste from clipboard',
      mode = { 'n', 'x' },
    },
    ['<leader>P'] = {
      key = '<leader>P',
      prev = 'try_to_paste_image_P',
      expr = true,
      desc = 'Paste from clipboard',
      mode = { 'n', 'x' },
    },
    ['gy'] = { key = 'gy', mode = { 'n', 'x' } },
  },
}
