return {
  enabled = true,
  keys = {
    ['af'] = { key = 'af', desc = 'Select around function', mode = { 'x', 'o' } },
    ['if'] = { key = 'if', desc = 'Select inside function', mode = { 'x', 'o' } },
    ['ac'] = { key = 'ac', mode = { 'x', 'o' }, desc = 'Select around class' },
    ['ic'] = { key = 'ic', mode = { 'x', 'o' }, desc = 'Select inside class' },
    ['ab'] = { key = 'ab', mode = { 'x', 'o' }, desc = 'Select around block' },
    ['ib'] = { key = 'ib', mode = { 'x', 'o' }, desc = 'Select inside block' },
    ['ai'] = { key = 'ai', mode = { 'x', 'o' }, desc = 'Select around if' },
    ['ii'] = { key = 'ii', mode = { 'x', 'o' }, desc = 'Select inside if' },
    ['al'] = { key = 'al', mode = { 'x', 'o' }, desc = 'Select around loop' },
    ['il'] = { key = 'il', mode = { 'x', 'o' }, desc = 'Select inside loop' },
    ['ar'] = { key = 'ar', mode = { 'x', 'o' }, desc = 'Select around return' },
    ['ir'] = { key = 'ir', mode = { 'x', 'o' }, desc = 'Select inside return' },
    ['ap'] = { key = 'ap', mode = { 'x', 'o' }, desc = 'Select around parameter' },
    ['ip'] = { key = 'ip', mode = { 'x', 'o' }, desc = 'Select inside parameter' },
    ['snf'] = { key = 'snf', desc = 'Swap with next function' },
    ['snc'] = { key = 'snc', desc = 'Swap with next class' },
    ['snl'] = { key = 'snl', desc = 'Swap with next loop' },
    ['snb'] = { key = 'snb', desc = 'Swap with next block' },
    ['snr'] = { key = 'snr', desc = 'Swap with next return' },
    ['snp'] = { key = 'snp', desc = 'Swap with next parameter' },
    ['sni'] = { key = 'sni', desc = 'Swap with next if' },
    ['spf'] = { key = 'spf', desc = 'Swap with previous function' },
    ['spc'] = { key = 'spc', desc = 'Swap with previous class' },
    ['spl'] = { key = 'spl', desc = 'Swap with previous loop' },
    ['spb'] = { key = 'spb', desc = 'Swap with previous block' },
    ['spr'] = { key = 'spr', desc = 'Swap with previous return' },
    ['spp'] = { key = 'spp', desc = 'Swap with previous parameter' },
    ['spi'] = { key = 'spi', desc = 'Swap with previous if' },
    ['[f'] = { key = '[f', desc = 'Previous function start', mode = { 'n', 'x', 'o' } },
    [']f'] = { key = ']f', desc = 'Next function start', mode = { 'n', 'x', 'o' } },
    ['[c'] = { key = '[c', desc = 'Previous class start', mode = { 'n', 'x', 'o' } },
    [']c'] = { key = ']c', desc = 'Next class start', mode = { 'n', 'x', 'o' } },
    ['[l'] = { key = '[l', desc = 'Previous loop start', mode = { 'n', 'x', 'o' } },
    [']l'] = { key = ']l', desc = 'Next loop start', mode = { 'n', 'x', 'o' } },
    ['[b'] = { key = '[b', desc = 'Previous block start', mode = { 'n', 'x', 'o' } },
    [']b'] = { key = ']b', desc = 'Next block start', mode = { 'n', 'x', 'o' } },
    ['[r'] = { key = '[r', desc = 'Previous return start', mode = { 'n', 'x', 'o' } },
    [']r'] = { key = ']r', desc = 'Next return start', mode = { 'n', 'x', 'o' } },
    ['[p'] = { key = '[p', desc = 'Previous parameter start', mode = { 'n', 'x', 'o' } },
    [']p'] = { key = ']p', desc = 'Next parameter start', mode = { 'n', 'x', 'o' } },
    ['[i'] = { key = '[i', desc = 'Previous if start', mode = { 'n', 'x', 'o' } },
    [']i'] = { key = ']i', desc = 'Next if start', mode = { 'n', 'x', 'o' } },
    ['[F'] = { key = '[F', desc = 'Previous function end', mode = { 'n', 'x', 'o' } },
    [']F'] = { key = ']F', desc = 'Next function end', mode = { 'n', 'x', 'o' } },
    ['[C'] = { key = '[C', desc = 'Previous class end', mode = { 'n', 'x', 'o' } },
    [']C'] = { key = ']C', desc = 'Next class end', mode = { 'n', 'x', 'o' } },
    ['[L'] = { key = '[L', desc = 'Previous loop end', mode = { 'n', 'x', 'o' } },
    [']L'] = { key = ']L', desc = 'Next loop end', mode = { 'n', 'x', 'o' } },
    ['[B'] = { key = '[B', desc = 'Previous block end', mode = { 'n', 'x', 'o' } },
    [']B'] = { key = ']B', desc = 'Next block end', mode = { 'n', 'x', 'o' } },
    ['[R'] = { key = '[R', desc = 'Previous return end', mode = { 'n', 'x', 'o' } },
    [']R'] = { key = ']R', desc = 'Next return end', mode = { 'n', 'x', 'o' } },
    ['[P'] = { key = '[P', desc = 'Previous parameter end', mode = { 'n', 'x', 'o' } },
    [']P'] = { key = ']P', desc = 'Next parameter end', mode = { 'n', 'x', 'o' } },
    ['[I'] = { key = '[I', desc = 'Previous if end', mode = { 'n', 'x', 'o' } },
    [']I'] = { key = ']I', desc = 'Next if end', mode = { 'n', 'x', 'o' } },
  },
}
