return {
  enabled = true,
  keys = {
    ['af'] = { key = 'af', prev = 'big_file_check', desc = 'Select around function', mode = { 'x', 'o' } },
    ['if'] = { key = 'if', prev = 'big_file_check', desc = 'Select inside function', mode = { 'x', 'o' } },
    ['ac'] = { key = 'ac', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select around class' },
    ['ic'] = { key = 'ic', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select inside class' },
    ['ab'] = { key = 'ab', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select around block' },
    ['ib'] = { key = 'ib', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select inside block' },
    ['ai'] = { key = 'ai', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select around if' },
    ['ii'] = { key = 'ii', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select inside if' },
    ['al'] = { key = 'al', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select around loop' },
    ['il'] = { key = 'il', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select inside loop' },
    ['ar'] = { key = 'ar', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select around return' },
    ['ir'] = { key = 'ir', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select inside return' },
    ['ap'] = { key = 'ap', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select around parameter' },
    ['ip'] = { key = 'ip', prev = 'big_file_check', mode = { 'x', 'o' }, desc = 'Select inside parameter' },
    ['snf'] = { key = 'snf', prev = 'big_file_check', desc = 'Swap with next function' },
    ['snc'] = { key = 'snc', prev = 'big_file_check', desc = 'Swap with next class' },
    ['snl'] = { key = 'snl', prev = 'big_file_check', desc = 'Swap with next loop' },
    ['snb'] = { key = 'snb', prev = 'big_file_check', desc = 'Swap with next block' },
    ['snr'] = { key = 'snr', prev = 'big_file_check', desc = 'Swap with next return' },
    ['snp'] = { key = 'snp', prev = 'big_file_check', desc = 'Swap with next parameter' },
    ['sni'] = { key = 'sni', prev = 'big_file_check', desc = 'Swap with next if' },
    ['spf'] = { key = 'spf', prev = 'big_file_check', desc = 'Swap with previous function' },
    ['spc'] = { key = 'spc', prev = 'big_file_check', desc = 'Swap with previous class' },
    ['spl'] = { key = 'spl', prev = 'big_file_check', desc = 'Swap with previous loop' },
    ['spb'] = { key = 'spb', prev = 'big_file_check', desc = 'Swap with previous block' },
    ['spr'] = { key = 'spr', prev = 'big_file_check', desc = 'Swap with previous return' },
    ['spp'] = { key = 'spp', prev = 'big_file_check', desc = 'Swap with previous parameter' },
    ['spi'] = { key = 'spi', prev = 'big_file_check', desc = 'Swap with previous if' },
    ['[f'] = { key = '[f', prev = 'big_file_check', desc = 'Previous function start', mode = { 'n', 'x', 'o' } },
    [']f'] = { key = ']f', prev = 'big_file_check', desc = 'Next function start', mode = { 'n', 'x', 'o' } },
    ['[c'] = { key = '[c', prev = 'big_file_check', desc = 'Previous class start', mode = { 'n', 'x', 'o' } },
    [']c'] = { key = ']c', prev = 'big_file_check', desc = 'Next class start', mode = { 'n', 'x', 'o' } },
    ['[l'] = { key = '[l', prev = 'big_file_check', desc = 'Previous loop start', mode = { 'n', 'x', 'o' } },
    [']l'] = { key = ']l', prev = 'big_file_check', desc = 'Next loop start', mode = { 'n', 'x', 'o' } },
    ['[b'] = { key = '[b', prev = 'big_file_check', desc = 'Previous block start', mode = { 'n', 'x', 'o' } },
    [']b'] = { key = ']b', prev = 'big_file_check', desc = 'Next block start', mode = { 'n', 'x', 'o' } },
    ['[r'] = { key = '[r', prev = 'big_file_check', desc = 'Previous return start', mode = { 'n', 'x', 'o' } },
    [']r'] = { key = ']r', prev = 'big_file_check', desc = 'Next return start', mode = { 'n', 'x', 'o' } },
    ['[p'] = { key = '[p', prev = 'big_file_check', desc = 'Previous parameter start', mode = { 'n', 'x', 'o' } },
    [']p'] = { key = ']p', prev = 'big_file_check', desc = 'Next parameter start', mode = { 'n', 'x', 'o' } },
    ['[i'] = { key = '[i', prev = 'big_file_check', desc = 'Previous if start', mode = { 'n', 'x', 'o' } },
    [']i'] = { key = ']i', prev = 'big_file_check', desc = 'Next if start', mode = { 'n', 'x', 'o' } },
    ['[F'] = { key = '[F', prev = 'big_file_check', desc = 'Previous function end', mode = { 'n', 'x', 'o' } },
    [']F'] = { key = ']F', prev = 'big_file_check', desc = 'Next function end', mode = { 'n', 'x', 'o' } },
    ['[C'] = { key = '[C', prev = 'big_file_check', desc = 'Previous class end', mode = { 'n', 'x', 'o' } },
    [']C'] = { key = ']C', prev = 'big_file_check', desc = 'Next class end', mode = { 'n', 'x', 'o' } },
    ['[L'] = { key = '[L', prev = 'big_file_check', desc = 'Previous loop end', mode = { 'n', 'x', 'o' } },
    [']L'] = { key = ']L', prev = 'big_file_check', desc = 'Next loop end', mode = { 'n', 'x', 'o' } },
    ['[B'] = { key = '[B', prev = 'big_file_check', desc = 'Previous block end', mode = { 'n', 'x', 'o' } },
    [']B'] = { key = ']B', prev = 'big_file_check', desc = 'Next block end', mode = { 'n', 'x', 'o' } },
    ['[R'] = { key = '[R', prev = 'big_file_check', desc = 'Previous return end', mode = { 'n', 'x', 'o' } },
    [']R'] = { key = ']R', prev = 'big_file_check', desc = 'Next return end', mode = { 'n', 'x', 'o' } },
    ['[P'] = { key = '[P', prev = 'big_file_check', desc = 'Previous parameter end', mode = { 'n', 'x', 'o' } },
    [']P'] = { key = ']P', prev = 'big_file_check', desc = 'Next parameter end', mode = { 'n', 'x', 'o' } },
    ['[I'] = { key = '[I', prev = 'big_file_check', desc = 'Previous if end', mode = { 'n', 'x', 'o' } },
    [']I'] = { key = ']I', prev = 'big_file_check', desc = 'Next if end', mode = { 'n', 'x', 'o' } },
  },
}
